accounts/urls.py
"""URL Configuration for Accounts
"""

__all__ = ["app_name", "urlpatterns"]
__author__ = "Advaith Menon"

from django.urls import include, path

from . import views as v

# Creates the 'accounts' namespace.
# app_name = "accounts"


# Describes the URLs in this namespace.
urlpatterns = [
        path("",
             include("django.contrib.auth.urls")),
        path("profile/<int:pk>/", v.ProfileView.as_view(), name="profile"),
        path("profile/<int:pk>/edit", v.ProfileUpdateView.as_view(),
             name="edit_profile"),
        path("profile/", v.my_profile, name="my_profile"),
        path("profile/pokemon", v.MyPokemonsListView.as_view(),
             name="my_pokemon"),
        path("signup/init", v.signup_v2_init, name="signup"),
        path("signup/verify/<str:token>", v.signup_v2_verify, name="sverify"),
        ]

poketrade2/urls.py
__all__ = ["urlpatterns"]
__author__ = "Advaith Menon et al."

from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    # URL for the Accounts app
    path("accounts/", include("accounts.urls")),
    path('admin/', admin.site.urls),
    # Trading gets root priority
    path("", include("trading.urls")),
]


# configure media uploads
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

trading/urls.py
"""URL Configuration for Trading
"""

__all__ = ["app_name", "urlpatterns"]
__author__ = "Advaith Menon"

from django.urls import include, path

from . import views as v

# Creates the 'accounts' namespace.
app_name = "trading"


# Describes the URLs in this namespace.
urlpatterns = [
        path("", v.PokemonListView.as_view(), name="list"),
        # path("pokemon/<int:pk>/", v.PokemonDetailView.as_view(),
        #      name="single_detail"),
        path("pokemon/<int:pk>/buy", v.BuyPokemonView.as_view(),
             name="buy_single"),
        path("pokemon/<int:pk>/", v.UpdateSellPriceView.as_view(),
             name="single_detail"),
        path("accounts/profile/<int:pk>/collection",
             v.UserPokemonListView.as_view(), name="user_collection"),
        path("accounts/profile/<int:pk>/wishlist",
             v.UserPokemonWishListView.as_view(), name="user_wl"),
        path("pokemon/<int:pk>/wish", v.WishPokemonView.as_view(),
             name="wish"),
        path("pokemon/<int:pk>/unwish", v.UnWishPokemonView.as_view(),
             name="unwish"),
        ]

accounts/models.py
"""User Models for Authentication.

Subclasses Django's default User Model to allow for more efficient
database queries. With a one-to-one relation, two queries would be
required for every profile attribute query:

#. ``SELECT user_id FROM users WHERE username=?``
#. ``SELECT * FROM profile WHERE user_id=?``

It is possible to do this with an inner join (``SELECT * from users,
profile WHERE users.user_id=? AND users.user_id = profile.user_id``),
but that has an equivalent database hit - two database tables have
to be queried.

One-to-one relations are generally a bad idea, since fields can be put
in the same table (unless of course you exceed the max column limit,
but you should seriously reconsider your design if you are near there.)
By putting fields along with the User object, querying becomes faster
and the database is free to do more work.
"""

__all__ = ["User"]
__author__ = "Advaith Menon"

import hashlib
from datetime import datetime, timedelta
from urllib.parse import urlencode

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.signals import user_logged_in
from django.conf import settings
from django.db import models
from django.contrib import messages


class User(AbstractUser):
    """Defines a PokeTrade2 User.

    A PokeTrade2 user consists of normal user attributes, as defined by
    Django, and some custom attributes, which are documented below.
    """

    # The coins owned by a user
    coins = models.IntegerField(default=0)

    # The user's streak
    streak = models.IntegerField(default=0)

    # The last time the user got a daily reward
    last_daily_reward = models.DateTimeField(null=True, blank=True)


    def gravatar(self, size=40, *, fallback="retro",
                 default="{username}@example.org"):
        """Get the User's Gravatar.

        To have a pseudo-Pokemon theme, the attribute ``wavatar`` is
        used if the avatar does not exist.

        If the email does not exist, the generated hash is of the
        form ``username@example.net``.

        :param size: The size of the image. Defult: 40.
        :type size: int
        :param fallback: The fallback avatar to use. Default: wavatar
        :type size: str
        :param default: The default email to use. Format specifiers
        ``username``, ``first``, ``last`` are replaced in .format()
        style.
        :type default: str
        :return: A string with the correct Gravatar URL.
        :rtype: str
        """
        # Get the user's email
        email = (self.email
                 or default.format(username=self.username,
                                   first=self.first_name,
                                   last=self.last_name))

        param = dict();

        # Get the hash
        hash = hashlib.sha256(email.encode()).hexdigest()
        param["d"] = fallback
        param["s"] = str(size)
        param["name"] = ' '.join((self.first_name or "", self.last_name or ""))
        param = urlencode(param);
        return "https://www.gravatar.com/avatar/{}?{}".format(hash, param)

    @property
    def gravatar_64(self):
        """Gravatar as a property for Django Templates.

        :return: A Gravatar URL of size 64 
        :rtype: str
        """
        return self.gravatar(64);

    @property
    def gravatar_128(self):
        """Gravatar as a property for Django Templates.

        :return: A Gravatar URL of size 128.
        :rtype: str
        """
        return self.gravatar(128);

    @property
    def gravatar_1024(self):
        """Gravatar as a property for Django Templates.

        :return: A Gravatar URL of size 1024.
        :rtype: str
        """
        return self.gravatar(1024);

# Signals

def signal_daily_reward(sender, request, user, **kwargs):
    """Signal for daily reward.

    :param sender: The class of the User object.
    :type sender: class`type`
    :param request: The HTTPRequest of the login object.
    :param user: The user who just logged in
    :type user: class`User`
    """
    if user.last_daily_reward is None \
            or datetime.now() - user.last_daily_reward.replace(tzinfo=None) \
            > timedelta(days=1):
        user.last_daily_reward = datetime.now()
        user.coins += settings.POKETRADE_DAILY_REWARD
        user.save()
        messages.info(request,
                      "You have received a daily reward of %d coins" % (
                          settings.POKETRADE_DAILY_REWARD))


user_logged_in.connect(signal_daily_reward)

accounts/forms.py
"""Forms for user creation"""

__author__ = "Advaith Menon"
__all__ = ["UserRegistrationRequestForm"]

from django import forms
from django.contrib.auth.forms import UserCreationForm \
        as OUserCreationForm

from .models import User


class UserRegistrationRequestForm(forms.Form):
    email = forms.EmailField(label="Email Address");
    first_name = forms.CharField(label="First Name", max_length=64);
    last_name = forms.CharField(label="Last Name", max_length=64);


class UserCreationForm(OUserCreationForm):
    class Meta(OUserCreationForm.Meta):
        model = User

accounts/views.py
"""Views for the Accounts app.

Contains signup pages and the profile page.
"""

__all__ = ["ProfileView", "ProfileUpdateView", "MyPokemonsListView",
           "my_profile", "signup_v2_init",
           "signup_v2_verify",]

__author__ = "Advaith Menon"

from time import time
from datetime import datetime

from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, reverse, render
from django.contrib import messages
from django.views.generic.edit import UpdateView
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
import jwt

from .models import User
from .forms import UserRegistrationRequestForm, \
        UserCreationForm
from trading.models import Pokemon
from trading.helpers import assign_pokemon_to_user


class MyPokemonsListView(LoginRequiredMixin, ListView):
    """Lists a users' owned Pokemon.
    """
    template_name = "accounts/my_pokemons.html"
    model = Pokemon
    context_object_name = "pokemons"

    def get_context_data(self, **kwargs):
        # to modify message on search
        ctx = super().get_context_data(**kwargs)
        ctx["query_str"] = self.request.GET.get("s", "")
        return ctx


    def get_queryset(self):
        if "s" in self.request.GET:
            # we have a search term
            term = self.request.GET["s"]
            return self.request.user.pokemons.filter(name__contains=term)
        return self.request.user.pokemons.all()


class ProfileView(LoginRequiredMixin, DetailView):
    """Enables viewing of profiles.
    """
    template_name = "accounts/user_detail.html"
    context_object_name = "the_user"
    model = User


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["username", "first_name", "last_name", "email"]
    # accounts/user_update.html
    template_name_suffix = "_update"

    def get_object(self, *args, **kw):
        """Get the object requested by the user.

        This is overriden to prevent users from editing each others'
        profiles.
        """
        obj = super().get_object(*args, **kw)
        if obj != self.request.user:
            # malicious user
            raise PermissionDenied
        return obj

    def get_success_url(self):
        """URL to redirect on success

        :return: A URL to redirect to on success
            This is the profile just edited.
        :rtype: str
        """
        return reverse("profile", kwargs=self.kwargs)


def my_profile(request):
    return redirect(reverse("profile", args=[request.user.pk]))


def signup_v2_init(request):
    form = UserRegistrationRequestForm()
    if request.method == "POST":
        form = UserRegistrationRequestForm(request.POST)
        if form.is_valid():
            if not User.objects.filter(email=form.cleaned_data["email"])\
                    .exists():
                token = jwt.encode({"email": form.cleaned_data["email"],
                            "first": form.cleaned_data["first_name"],
                            "last": form.cleaned_data["last_name"],
                            "exp": time() + 600},
                           settings.SECRET_KEY,
                           algorithm="HS256")
                link = request.get_host() + reverse("sverify",
                                                  kwargs=dict(token=token))
                send_mail(
                        "[PokeTrade] Account Registration Request",
                        render_to_string("accounts/signup_v2_init.txt",
                             dict(email=form.cleaned_data["email"],
                                  link=link)),
                             settings.SERVER_EMAIL,
                             [form.cleaned_data["email"]],
                             fail_silently=False
                         )
            messages.success(request, "Check your email inbox")
            return redirect(reverse("trading:list"))
    return render(request, "accounts/signup_v2_init.html",
              dict(form=form))


def signup_v2_verify(request, token):
    try:
        token = jwt.decode(token, settings.SECRET_KEY,
                           algorithms=["HS256"])
        if request.method == "GET":
            if User.objects.filter(email=token["email"]).exists():
                raise RuntimeError("User exists")
            form = UserCreationForm()
            return render(request, "accounts/signup_v2_verify.html",
                          dict(form=form,
                               exp=datetime.fromtimestamp(token["exp"])))
        elif request.method == "POST":
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.email = token["email"]
                user.first_name = token["first"]
                user.last_name = token["last"]
                assign_pokemon_to_user(user)
                user.save()
                messages.success(request, "user created login now to get $$$")
                return redirect(reverse("trading:list"))
            else:
                form = form
                return render(request, "accounts/signup_v2_verify.html",
                              dict(form=form,
                                   exp=datetime.fromtimestamp(token["exp"])))
    except Exception as e:
        print(e)
        messages.error(request, "Link expired or user exists")
        return redirect(reverse("trading:list"))

accounts/templates/accounts/my_pokemons.html
{% extends "base.html" %}
{% block title %}My Pokemons{% endblock %}

{% block content %}
<h1>My Pokemons</h1>
<hr>

{% if not pokemons %}
<div class="message msg-info">
    {% if query_str %}
    You have no such Pokemon.
    {% else %}
    You have no Pokemons. Go and trade!
    {% endif %}
</div>
{% endif %}

<form method="GET">
    <input type="text" name="s" placeholder="Search..."
        value="{{ query_str }}">
    <input type="submit" value="Search">
</form>

<table>
    <tr>
        <th>Name</th>
        <th>HP</th>
        <th>Type</th>
        <th>Worth</th>
        <th>More Info</th>
    </tr>
    {% for pokemon in pokemons %}
    <tr>
        <td>{{ pokemon.name }}</td>
        <td>{{ pokemon.hp }}</td>
        <td>{{ pokemon.type_l }}</td>
        <td>{{ pokemon.cost_price }}</td>
        <td><a href="#">more...</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

accounts/templates/accounts/signup_v2_check_inbox.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
            <div class="message msg-info">
                {% translate "Check your inbox for instructions" %}
            </div>
{% endblock %}

accounts/templates/accounts/signup_v2_init.html
{% extends "base.html" %}
{% block content %}

    <style>
    .heading {
        margin-bottom: 15px;
    }

    .login-button {
        background-color: blue;
        border: none;
        padding: 10px 20px;
        border-radius: 8px;
        color: white;
        font-weight: bold;
        cursor: pointer;
        margin-top: 10px;
    }
    </style>

    <div class="container">
        <h1 class="heading"> Sign Up </h1>
    </div>
    <div class="row justify-content-center">
        <div class="col-6">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="row justify-content-center">
                    <input class="login-button" type="submit" value="Send Link">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup_v2_verify.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <style>
    .row {
        color: black;
    }

    .heading {
        color: black;
    }

    .login-button {
        background-color: blue;
        border: none;
        padding: 10px 20px;
        border-radius: 8px;
        color: white;
        font-weight: bold;
        cursor: pointer;
        margin-top: 10px;
    }
    </style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow p-3 mb-4 rounded">
                <div class="card-body">
                    <h2 class="heading">{% translate "Sign Up: Final Step" %}</h2>
                    <hr />
                    <div class="alert alert-warning">
                        You have until {{ exp|date:"m/d/Y H:i:s" }} to finish
                        your registration.
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="row justify-content-center">
                            <input class="login-button" type="submit" value="Sign Up">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends "base.html" %}
{% block title %}{{ the_user.username }}'s profile{% endblock %}

{% block content %}
    <style>
        .card {
            background-color: transparent;
            padding: 20px;
            color: white;
            font-family: "Kumbh Sans";
            font-size: 20px;
            max-width: 800px;
            margin: auto;
            border: transparent;
        }

        .entries {
            font-size: 35px;
        }
        .card .info-section {
            padding: 20px;
            color: #fff;
            display: flex;
            flex-direction: row;
            gap: 20px;
            flex-wrap: wrap;
            align-items: flex-start;
        }

        .card .info-text {
            margin-left: 10px;
            flex: 1;
            min-width: 250px;
        }

        .card .image-right {
            flex-shrink: 0;
            align-self: flex-start;
            max-width: 280px;
        }

        .card .image-right img {
            border-radius: 8px;
        }

    @media (max-width: 800px) {
        .card .info-section {
            flex-direction: row;
            align-items: flex-start;
            justify-content: space-between;
            flex-wrap: wrap;
        }

        .card .info-text {
            flex: 1 1 60%;
            min-width: 0;
        }

        .card .image-right {
            flex: 0 0 auto;
            align-self: flex-start;
            max-width: 280px;
        }

        .card .image-right img {
            max-width: 80%;
            height: auto;
        }

        .entries {
            justify-content: center;
            margin: 0px;
            font-size: 35px;
        }
    }
    </style>
    <div class="d-flex justify-content-center">
            <div class="p-2 profhead">Profile</div>
        </div>
    <div class="card">

        <div class="info-section">
            <div class="image-right">
                <div class="row justify-content-center">
                    <img class="profpic" src="{{ the_user.gravatar_1024 }}" alt="">
                </div>
            </div>
            <div class="info-text">
                <div class="row entries">Username: {{ the_user.username }}</div>
                {% if the_user.first_name %}
                    <div class="row entries">First Name: {{ the_user.first_name }}</div>
                {% endif %}
                {% if the_user.last_name %}
                    <div class="row entries">Last Name: {{ the_user.last_name }}</div>
                {% endif %}
                <div class="row entries">Coins: {{ the_user.coins }}</div>
                <div class="row entries">Streak: {{ the_user.streak }}</div>
            </div>
        </div>
        {% if the_user == user %}
            <div class="d-flex justify-content-center">
                <a href="{% url 'edit_profile' user.pk %}">
                    <button class="edit_prof_btn" >Edit Profile</button>
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}

accounts/templates/accounts/user_update.html
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
    <style>
    .entries {
        font-size: 35px;
    }
    .editprofform {
        border: none;
        margin-bottom: 15px;
        max-width: 100%;
    }
    .editproflabel {
        min-width: 22%;
        text-align: left;
    }
    </style>
<div class="container-fluid">
    <div class="d-flex justify-content-center">
        <div class="p-2 profhead">Edit Profile</div>
    </div>

        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row entries justify-content-center">
                {{ form.username.errors }}
                <label class="editproflabel" for="{{ form.username.id_for_label }}">Username: </label>
                <input class="editprofform" type="text" name="username" value="{{ user.username }}" maxlength="150" required="" aria-describedby="id_username_helptext" id="id_username">
            </div>
            <div class="row entries justify-content-center">
                {{ form.first_name.errors }}
                <label class="editproflabel" for="{{ form.first_name.id_for_label }}">First Name: </label>
                <input class="editprofform" type="text" name="first_name" value="{{ user.first_name }}" maxlength="150" id="id_first_name">
            </div>
            <div class="row entries justify-content-center">
                {{ form.last_name.errors }}
                <label class="editproflabel" for="{{ form.last_name.id_for_label }}">Last Name: </label>
                <input class="editprofform" type="text" name="last_name" value="{{ user.last_name }}" maxlength="150" id="id_last_name">
            </div>
            <div class="row entries justify-content-center">
                {{ form.email.errors }}
                <label class="editproflabel" for="{{ form.email.id_for_label }}">Email address: </label>
                <input class="editprofform" type="email" name="email" value="{{ user.email }}" maxlength="254" id="id_email">
            </div>
            <div class="d-flex justify-content-center">
                    <input class="edit_prof_btn" type="submit" value="Update">
            </div>

        </form>

</div>

{% endblock %}