accounts/urls.py
"""URL Configuration for Accounts
"""

__all__ = ["app_name", "urlpatterns"]
__author__ = "Advaith Menon"

from django.urls import include, path

from . import views as v

# Creates the 'accounts' namespace.
# app_name = "accounts"


# Describes the URLs in this namespace.
urlpatterns = [
        path("",
             include("django.contrib.auth.urls")),
        path("profile/<int:pk>/", v.ProfileView.as_view(), name="profile"),
        path("profile/<int:pk>/edit", v.ProfileUpdateView.as_view(),
             name="edit_profile"),
        path("profile/", v.my_profile, name="my_profile"),
        path("profile/pokemon", v.MyPokemonsListView.as_view(),
             name="my_pokemon"),
        path("signup/init", v.signup_v2_init, name="signup"),
        path("signup/verify/<str:token>", v.signup_v2_verify, name="sverify"),
        ]

poketrade2/urls.py
__all__ = ["urlpatterns"]
__author__ = "Advaith Menon et al."

from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    # URL for the Accounts app
    path("accounts/", include("accounts.urls")),
    path('admin/', admin.site.urls),
    # Trading gets root priority
    path("", include("trading.urls")),
]


# configure media uploads
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

trading/urls.py
"""URL Configuration for Trading
"""

__all__ = ["app_name", "urlpatterns"]
__author__ = "Advaith Menon"

from django.urls import include, path

from . import views as v

# Creates the 'accounts' namespace.
app_name = "trading"


# Describes the URLs in this namespace.
urlpatterns = [
        path("", v.PokemonListView.as_view(), name="list"),
        # path("pokemon/<int:pk>/", v.PokemonDetailView.as_view(),
        #      name="single_detail"),
        path("pokemon/<int:pk>/buy", v.BuyPokemonView.as_view(),
             name="buy_single"),
        path("pokemon/<int:pk>/", v.UpdateSellPriceView.as_view(),
             name="single_detail"),
        path("accounts/profile/<int:pk>/collection",
             v.UserPokemonListView.as_view(), name="user_collection"),
        path("accounts/profile/<int:pk>/wishlist",
             v.UserPokemonWishListView.as_view(), name="user_wl"),
        path("pokemon/<int:pk>/wish", v.WishPokemonView.as_view(),
             name="wish"),
        path("pokemon/<int:pk>/unwish", v.UnWishPokemonView.as_view(),
             name="unwish"),
        ]

accounts/models.py
"""User Models for Authentication.

Subclasses Django's default User Model to allow for more efficient
database queries. With a one-to-one relation, two queries would be
required for every profile attribute query:

#. ``SELECT user_id FROM users WHERE username=?``
#. ``SELECT * FROM profile WHERE user_id=?``

It is possible to do this with an inner join (``SELECT * from users,
profile WHERE users.user_id=? AND users.user_id = profile.user_id``),
but that has an equivalent database hit - two database tables have
to be queried.

One-to-one relations are generally a bad idea, since fields can be put
in the same table (unless of course you exceed the max column limit,
but you should seriously reconsider your design if you are near there.)
By putting fields along with the User object, querying becomes faster
and the database is free to do more work.
"""

__all__ = ["User"]
__author__ = "Advaith Menon"

import hashlib
from datetime import datetime, timedelta
from urllib.parse import urlencode

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.signals import user_logged_in
from django.conf import settings
from django.db import models
from django.contrib import messages


class User(AbstractUser):
    """Defines a PokeTrade2 User.

    A PokeTrade2 user consists of normal user attributes, as defined by
    Django, and some custom attributes, which are documented below.
    """

    # The coins owned by a user
    coins = models.IntegerField(default=0)

    # The user's streak
    streak = models.IntegerField(default=0)

    # The last time the user got a daily reward
    last_daily_reward = models.DateTimeField(null=True, blank=True)


    def gravatar(self, size=40, *, fallback="retro",
                 default="{username}@example.org"):
        """Get the User's Gravatar.

        To have a pseudo-Pokemon theme, the attribute ``wavatar`` is
        used if the avatar does not exist.

        If the email does not exist, the generated hash is of the
        form ``username@example.net``.

        :param size: The size of the image. Defult: 40.
        :type size: int
        :param fallback: The fallback avatar to use. Default: wavatar
        :type size: str
        :param default: The default email to use. Format specifiers
        ``username``, ``first``, ``last`` are replaced in .format()
        style.
        :type default: str
        :return: A string with the correct Gravatar URL.
        :rtype: str
        """
        # Get the user's email
        email = (self.email
                 or default.format(username=self.username,
                                   first=self.first_name,
                                   last=self.last_name))

        param = dict();

        # Get the hash
        hash = hashlib.sha256(email.encode()).hexdigest()
        param["d"] = fallback
        param["s"] = str(size)
        param["name"] = ' '.join((self.first_name or "", self.last_name or ""))
        param = urlencode(param);
        return "https://www.gravatar.com/avatar/{}?{}".format(hash, param)

    @property
    def gravatar_64(self):
        """Gravatar as a property for Django Templates.

        :return: A Gravatar URL of size 64 
        :rtype: str
        """
        return self.gravatar(64);

    @property
    def gravatar_128(self):
        """Gravatar as a property for Django Templates.

        :return: A Gravatar URL of size 128.
        :rtype: str
        """
        return self.gravatar(128);

    @property
    def gravatar_1024(self):
        """Gravatar as a property for Django Templates.

        :return: A Gravatar URL of size 1024.
        :rtype: str
        """
        return self.gravatar(1024);

# Signals

def signal_daily_reward(sender, request, user, **kwargs):
    """Signal for daily reward.

    :param sender: The class of the User object.
    :type sender: class`type`
    :param request: The HTTPRequest of the login object.
    :param user: The user who just logged in
    :type user: class`User`
    """
    if user.last_daily_reward is None \
            or datetime.now() - user.last_daily_reward.replace(tzinfo=None) \
            > timedelta(days=1):
        user.last_daily_reward = datetime.now()
        user.coins += settings.POKETRADE_DAILY_REWARD
        user.save()
        messages.info(request,
                      "You have received a daily reward of %d coins" % (
                          settings.POKETRADE_DAILY_REWARD))


user_logged_in.connect(signal_daily_reward)

accounts/forms.py
"""Forms for user creation"""

__author__ = "Advaith Menon"
__all__ = ["UserRegistrationRequestForm"]

from django import forms
from django.contrib.auth.forms import UserCreationForm \
        as OUserCreationForm

from .models import User


class UserRegistrationRequestForm(forms.Form):
    email = forms.EmailField(label="Email Address");
    first_name = forms.CharField(label="First Name", max_length=64);
    last_name = forms.CharField(label="Last Name", max_length=64);


class UserCreationForm(OUserCreationForm):
    class Meta(OUserCreationForm.Meta):
        model = User

accounts/views.py
"""Views for the Accounts app.

Contains signup pages and the profile page.
"""

__all__ = ["ProfileView", "ProfileUpdateView", "MyPokemonsListView",
           "my_profile", "signup_v2_init",
           "signup_v2_verify",]

__author__ = "Advaith Menon"

from time import time
from datetime import datetime

from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, reverse, render
from django.contrib import messages
from django.views.generic.edit import UpdateView
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
import jwt

from .models import User
from .forms import UserRegistrationRequestForm, \
        UserCreationForm
from trading.models import Pokemon
from trading.helpers import assign_pokemon_to_user


class MyPokemonsListView(LoginRequiredMixin, ListView):
    """Lists a users' owned Pokemon.
    """
    template_name = "accounts/my_pokemons.html"
    model = Pokemon
    context_object_name = "pokemons"

    def get_context_data(self, **kwargs):
        # to modify message on search
        ctx = super().get_context_data(**kwargs)
        ctx["query_str"] = self.request.GET.get("s", "")
        return ctx


    def get_queryset(self):
        if "s" in self.request.GET:
            # we have a search term
            term = self.request.GET["s"]
            return self.request.user.pokemons.filter(name__contains=term)
        return self.request.user.pokemons.all()


class ProfileView(LoginRequiredMixin, DetailView):
    """Enables viewing of profiles.
    """
    template_name = "accounts/user_detail.html"
    context_object_name = "the_user"
    model = User


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["username", "first_name", "last_name", "email"]
    # accounts/user_update.html
    template_name_suffix = "_update"

    def get_object(self, *args, **kw):
        """Get the object requested by the user.

        This is overriden to prevent users from editing each others'
        profiles.
        """
        obj = super().get_object(*args, **kw)
        if obj != self.request.user:
            # malicious user
            raise PermissionDenied
        return obj

    def get_success_url(self):
        """URL to redirect on success

        :return: A URL to redirect to on success
            This is the profile just edited.
        :rtype: str
        """
        return reverse("profile", kwargs=self.kwargs)


def my_profile(request):
    return redirect(reverse("profile", args=[request.user.pk]))


def signup_v2_init(request):
    form = UserRegistrationRequestForm()
    if request.method == "POST":
        form = UserRegistrationRequestForm(request.POST)
        if form.is_valid():
            if not User.objects.filter(email=form.cleaned_data["email"])\
                    .exists():
                token = jwt.encode({"email": form.cleaned_data["email"],
                            "first": form.cleaned_data["first_name"],
                            "last": form.cleaned_data["last_name"],
                            "exp": time() + 600},
                           settings.SECRET_KEY,
                           algorithm="HS256")
                link = request.get_host() + reverse("sverify",
                                                  kwargs=dict(token=token))
                send_mail(
                        "[PokeTrade] Account Registration Request",
                        render_to_string("accounts/signup_v2_init.txt",
                             dict(email=form.cleaned_data["email"],
                                  link=link)),
                             settings.SERVER_EMAIL,
                             [form.cleaned_data["email"]],
                             fail_silently=False
                         )
            messages.success(request, "Check your email inbox")
            return redirect(reverse("trading:list"))
    return render(request, "accounts/signup_v2_init.html",
              dict(form=form))


def signup_v2_verify(request, token):
    try:
        token = jwt.decode(token, settings.SECRET_KEY,
                           algorithms=["HS256"])
        if request.method == "GET":
            if User.objects.filter(email=token["email"]).exists():
                raise RuntimeError("User exists")
            form = UserCreationForm()
            return render(request, "accounts/signup_v2_verify.html",
                          dict(form=form,
                               exp=datetime.fromtimestamp(token["exp"])))
        elif request.method == "POST":
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.email = token["email"]
                user.first_name = token["first"]
                user.last_name = token["last"]
                assign_pokemon_to_user(user)
                user.save()
                messages.success(request, "user created login now to get $$$")
                return redirect(reverse("trading:list"))
            else:
                form = form
                return render(request, "accounts/signup_v2_verify.html",
                              dict(form=form,
                                   exp=datetime.fromtimestamp(token["exp"])))
    except Exception as e:
        print(e)
        messages.error(request, "Link expired or user exists")
        return redirect(reverse("trading:list"))

accounts/templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100..900&display=swap" rel="stylesheet">
    <title>{% block title %}PokeTrade{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent justify-content-between">
        <img class="navbar_image" src="{% static '/refimages/title.png' %}">


        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <span class="coin_display"><img class="coins" src="{% static '/refimages/coin.png' %}">{{ user.coins }}</span>
                    <li class="nav-item"><a type="button" class="nav-link" href="{% url "trading:list" %}">Home</a></li>
                    <li class="nav-item"><a type="button" class="nav-link" href="{% url "trading:list" %}?q=sell_price%2CGT%2C0">Market</a></li>
                    <li class="nav-item"><a type="button" class="nav-link" href="{% url "trading:user_collection" user.pk %}">Collection</a></li>
                    <li class="nav-item"><a type="button" class="nav-link" href="{% url "trading:user_wl" user.pk %}">Wishlist</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'my_profile' %}">
                            <img href class="profile_BTN" src="{% static '/refimages/profile.png' %}">
                        </a>
                    </li>
                    <li class="nav-item">
                        <a type="button" class="nav-link">
                            <form method="post" action="{% url 'logout' %}" >
                                {% csrf_token %}
                                <button class="btn btn-link">Log Out</button>
                            </form>
                        </a>
                    </li>
                {% else %}
                    <a class="nav-link" href="{% url 'signup' %}">SignUp</a>
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}
            </ul>
        </div>
    </nav>
    <img src="{% static '/refimages/title.png' %}" class="title_image">

    <div class="container">
    {% if messages %}
            {% for message in messages %}
                <!--modify here-->
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="row mb-3">
            <div class="col-12">
                <button id="go-back" class="back-button-arrow" style="display: none;">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M19 12H5" stroke="#DD092F" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M12 19L5 12L12 5" stroke="#DD092F" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </button>
            </div>
        </div>
        
        <div class="row mb-3">
            <div class="col-12">
                <button id="go-back" class="back-button-arrow" style="display: none;">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M19 12H5" stroke="#DD092F" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M12 19L5 12L12 5" stroke="#DD092F" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </button>
            </div>
        </div>
        
        {% block content %}
            <div id="image-row"></div>
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const backButton = document.getElementById('go-back');
            
            if (backButton) {
                const currentPath = window.location.pathname;
                const currentURL = window.location.href;

                const loginPages = [
                    '/accounts/login/',
                    '/accounts/signup/',
                    '/accounts/logout/'
                ];
  
                const hideOnPages = [
                    '/trading/list/', 
                    ...loginPages
                ];

                const showOnPages = [
                    '/collection',
                    '/wishlist',
                    '/accounts/profile/',
                    'profile/1/collection',
                    'profile/2/collection',
                    'edit',
                    '?q=sell_price'
                ];

                const isLoginPage = loginPages.some(path => currentPath === path || currentPath.includes(path));
                
                const shouldAlwaysShow = showOnPages.some(path => 
                    currentPath.includes(path) || currentURL.includes(path)
                );

                const shouldNeverShow = hideOnPages.some(path => 
                    currentPath === path
                );
                
                const isFirstLoad = window.history.length <= 1;

                if ((shouldAlwaysShow || !shouldNeverShow) && !isFirstLoad) {
                    if (isLoginPage || document.referrer.includes('/accounts/login/')) {
                        backButton.style.display = 'none';
                    } else {
                        backButton.style.display = 'flex';
                        
                        backButton.addEventListener('click', function(e) {
                            e.preventDefault();

                            const curPath = window.location.pathname;

                            const referrer = document.referrer;

                            if (loginPages.some(page => referrer.includes(page))) {
                                window.location.href = '/trading/list/';
                            } else {
                                if (curPath.includes('/pokemon/') || 
                                    curPath.includes('/buy/') || 
                                    curPath.includes('/wish/') ||
                                    curPath.includes('/unwish/')) {

                                    sessionStorage.setItem('needsRefresh', 'true');
                                }
                                
                                window.history.back();
                            }
                        });
                    }
                }
            }
            
            window.addEventListener('pageshow', function(event) {
                if (event.persisted || (window.performance && window.performance.navigation.type === 2)) {
                    if (sessionStorage.getItem('needsRefresh') === 'true') {
                        sessionStorage.removeItem('needsRefresh');
                        window.location.reload();
                    }
                    
                    const currentPath = window.location.pathname;
                    if (currentPath.includes('/accounts/login/') || 
                        currentPath.includes('/accounts/signup/') || 
                        currentPath.includes('/accounts/logout/')) {
                        window.location.reload(true);
                    }
                }
            });
        });
    </script>
</body>
</html>