poketrade2/urls.py
__all__ = ["urlpatterns"]
__author__ = "Advaith Menon et al."

from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    # URL for the Accounts app
    path("accounts/", include("accounts.urls")),
    path('admin/', admin.site.urls),
    # Trading gets root priority
    path("", include("trading.urls")),
]


# configure media uploads
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

trading/urls.py
"""URL Configuration for Trading
"""

__all__ = ["app_name", "urlpatterns"]
__author__ = "Advaith Menon"

from django.urls import include, path

from . import views as v

# Creates the 'accounts' namespace.
app_name = "trading"


# Describes the URLs in this namespace.
urlpatterns = [
        path("", v.PokemonListView.as_view(), name="list"),
        # path("pokemon/<int:pk>/", v.PokemonDetailView.as_view(),
        #      name="single_detail"),
        path("pokemon/<int:pk>/buy", v.BuyPokemonView.as_view(),
             name="buy_single"),
        path("pokemon/<int:pk>/", v.UpdateSellPriceView.as_view(),
             name="single_detail"),
        path("accounts/profile/<int:pk>/collection",
             v.UserPokemonListView.as_view(), name="user_collection"),
        path("accounts/profile/<int:pk>/wishlist",
             v.UserPokemonWishListView.as_view(), name="user_wl"),
        path("pokemon/<int:pk>/wish", v.WishPokemonView.as_view(),
             name="wish"),
        path("pokemon/<int:pk>/unwish", v.UnWishPokemonView.as_view(),
             name="unwish"),
        ]

trading/views.py
"""Views for Trading

With the exception of the "My Pokemon" page, all other pages
be under the Trading app.
"""

__all__ = ["PokemonListView", "PokemonDetailView",
           "UserPokemonListView", "BuyPokemonView",
           "UpdateSellPriceView", "UserPokemonWishListView",
           "WishPokemonView", "UnWishPokemonView"]
__author__ = "Advaith Menon"

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import get_object_or_404, reverse, redirect
from django.contrib import messages
from django.db.models import Q

from accounts.models import User
from .models import Pokemon, TradingPolicy
from .helpers import QueryParser, QueryableMixin


class PokemonListView(QueryableMixin, ListView):
    """Lists all Pokemon.
    """
    # template name is trading/pokemon_list.html
    # the default ^^ is okay
    model = Pokemon
    context_object_name = "pokemons"
    paginate_by = 100

    # defines the custom query
    generic_qparse = QueryParser(valid_fields={"name": str, "hp": int,
                            "rarity": str, "sell_price": float,
                            "owner__username": str})


class UserPokemonListView(QueryableMixin, LoginRequiredMixin, ListView):
    """Lists a single users' Pokemon.
    """
    model = Pokemon
    context_object_name = "pokemons"
    paginate_by = 100

    def get_queryset(self):
        # print("kwe:", type(self.kwargs.get("pk")))
        return super().get_queryset() \
                .filter(owner__pk__exact=self.kwargs.get("pk"))


class UserPokemonWishListView(QueryableMixin, LoginRequiredMixin, ListView):
    """Lists a single users' Pokemon wishlist
    """
    model = User
    context_object_name = "pokemons"
    paginate_by = 100

    # defines the custom query
    generic_qparse = QueryParser(valid_fields={"name": str, "hp": int,
                            "rarity": str, "sell_price": float,
                            "owner__username": str})

    def get_queryset(self):
        if self._get_userquery() is not None:
            return get_object_or_404(self.model, pk=self.kwargs["pk"]) \
                    .wishlist.filter(self._get_pu())
        return get_object_or_404(self.model, pk=self.kwargs["pk"]) \
                .wishlist.all()


class BuyPokemonView(LoginRequiredMixin, TemplateView):
    """Buys a pokemon if the request is POST.
    """
    http_method_names = ["post", "options"]
    template_name = "trading/bought_pokemon.html"

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # copied from the source code of the LogoutView
        # TL;DR provides CSRF protection
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        pok_id = self.kwargs["pk"]
        pok_obj = get_object_or_404(Pokemon, Q(pk=pok_id)
                                    & ~Q(owner=self.request.user))
        if pok_obj.trading_policy != TradingPolicy.FOR_SALE:
            messages.error(request, "You cannot buy PokeMon not for sale!!!")
            return redirect(reverse("trading:single_detail", args=[pok_id]))


        # subtract its sell price to your account
        if self.request.user.coins < pok_obj.sell_price:
            messages.error(request,
                           "You don't have enough coins to buy PokeMon")
            return redirect(reverse("trading:single_detail",
                            kwargs={"pk":pok_id}))
        self.request.user.coins -= pok_obj.sell_price

        # add sell price to owner (if exists)
        if pok_obj.owner:
            pok_obj.owner.coins += pok_obj.sell_price
            pok_obj.owner.save()

        # make POK's cost price the sell price
        pok_obj.cost_price = pok_obj.sell_price

        # make sell price 0
        pok_obj.sell_price = 0

        # update owner
        pok_obj.owner = self.request.user

        # save both
        self.request.user.save()
        pok_obj.save()
        messages.success(request, "The pokemon is now yours")
        return redirect(reverse("trading:single_detail", kwargs={"pk":pok_id}))
        #return super().get(request, *args, **kwargs)


class UnWishPokemonView(LoginRequiredMixin, TemplateView):
    """Wish a pokemon if the request is POST.
    """
    http_method_names = ["post", "delete", "options"]
    template_name = "trading/bought_pokemon.html"

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # copied from the source code of the LogoutView
        # TL;DR provides CSRF protection
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        pok_id = self.kwargs["pk"]
        pok_obj = get_object_or_404(Pokemon, pk=pok_id)
        pok_obj.wishers.remove(request.user)
        pok_obj.save()
        messages.success(request, "Pokemon removed from wishlist")
        return redirect(reverse("trading:user_wl", args=[request.user.pk]))


class WishPokemonView(LoginRequiredMixin, TemplateView):
    """Wish a pokemon if the request is POST.
    """
    http_method_names = ["post", "delete", "options"]
    template_name = "trading/pokemon_list.html"

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # copied from the source code of the LogoutView
        # TL;DR provides CSRF protection
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        pok_id = self.kwargs["pk"]
        pok_obj = get_object_or_404(Pokemon, pk=pok_id)
        pok_obj.wishers.add(request.user)
        pok_obj.save()
        messages.success(request, "Pokemon added to wishlist")
        return redirect(reverse("trading:user_wl", args=[request.user.pk]))

    def delete(self, request, *args, **kwargs):
        pok_id = self.kwargs["pk"]
        pok_obj = get_object_or_404(Pokemon, pk=pok_id)
        pok_obj.wishers.delete(request.user)
        pok_obj.save()
        messages.success(request, "Pokemon removed from wishlist")
        return super().get(request, *args, **kwargs)


class UpdateSellPriceView(LoginRequiredMixin, UpdateView):
    model = Pokemon
    fields = ["sell_price"]
    # trading/pokemon_update.html
    template_name = "trading/pokemon_detail.html"
    context_object_name = "the_pokemon"
    #template_name_suffix = "_update"
    # template_name_suffix = "_update"

    def get_object(self, *args, **kw):
        """Get the object requested by the user.

        This is overriden to prevent users from selling each others'
        pokemon
        """
        obj = super().get_object(*args, **kw)

        return obj

    def get_success_url(self):
        """URL to redirect on success

        :return: A URL to redirect to on success
            This is the profile just edited.
        :rtype: str
        """
        messages.success(self.request, "Updated sale price!")
        return reverse("trading:single_detail", args=[self.object.pk])

    def get_context_data(self, **kwargs):
        # to modify message on search
        ctx = super().get_context_data(**kwargs)
        ctx["in_wishlist"] = \
            self.get_object().wishers.filter(pk=self.request.user.pk).exists()
        return ctx


class PokemonDetailView(DetailView):
    # template: trading/pokemon_detail.html
    model = Pokemon
    context_object_name = "the_pokemon"

    def get_context_data(self, **kwargs):
        # to modify message on search
        ctx = super().get_context_data(**kwargs)
        ctx["in_wishlist"] = \
            self.get_object().wishers.filter(pk=self.request.user.pk).exists()
        return ctx

trading/templates/trading/bought_pokemon.html
{% extends "base.html" %}
{% block title %}Bought Pokemon{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="heading">Success</h1>
    </div>
    <div class="row justify-content-center">
        <div class="col-auto">
            <p>The pokemon is now yours.</p>
        </div>
    </div>
{% endblock %}

trading/templates/trading/confirmation_buy.html
<div id="sellModal" class="modal">
    <div class="modal-content">
      <p>Are you sure you want to buy <strong>{{ the_pokemon.name }}</strong> for <strong>{{ cost_price }}</strong> coins?</p>
      <form method="POST" action="{% url 'sell_pokemon' the_pokemon.id %}"> 
        {% csrf_token %}
        <div class="modal-buttons">
          <button type="submit" onClick="buyPokemon()">Yes</button>
          <button type="button" onclick="closeModal()">No</button>
        </div>
      </form>
    </div>
  </div>

trading/templates/trading/pokemon_detail.html
{% extends "base.html" %}
{% block title %}{{ the_pokemon.name }} - Stats{% endblock %}

{% block content %}
<style>

.card {
    background-color: #f44336;
    border-radius: 20px;
    padding: 20px;
    color: white;
    font-family: "Kumbh Sans";
    font-size: 20px;
    max-width: 800px;
    margin: auto;
}

.card .info-section {
    border-radius: 12px;
    padding: 20px;
    color: #fff;
    display: flex;
    flex-direction: row;
    gap: 20px;
    flex-wrap: wrap;
    align-items: flex-start;
}

.card .info-text {
    flex: 1;
    min-width: 250px;
}

.card .image-right {
    flex-shrink: 0;
    align-self: flex-start;
}

.card .image-right img {
    width: 200px;
    border-radius: 8px;
}

.types {
    display: flex;
}

.types span {
    background-color: black;
    color: white;
    padding: 3px 8px;
    border-radius: 5px;
    margin-right: 5px;
}
.subtypes {
    display: flex;
}

.subtypes li {
    display: inline;
    margin-right: 8px;
    background: black;
    padding: 3px 6px;
    border-radius: 5px;
}
.price {
    display: flex;
    min-width: 40%;
}

.nametag {
    margin-left: 5px;
}

.info-label {
    font-weight: bold;
    margin-top: 10px;
    display: inline-block;
}

.buy-button {
    background-color: #00e676;
    border: none;
    padding: 10px 20px;
    border-radius: 8px;
    color: black;
    font-weight: bold;
    margin-top: 20px;
    cursor: pointer;
}

.sell-button {
    background-color: darkred;
    border: none;
    padding: 10px 20px;
    border-radius: 8px;
    color: #FFCC03;
    font-weight: bold;
    margin-top: 20px;
    cursor: pointer;
}

.buttons-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-top: 20px;
    gap: 10px;
}

@media (max-width: 800px) {
  .card .info-section {
    flex-direction: row;
    align-items: flex-start;
    justify-content: space-between;
    flex-wrap: wrap-reverse;
  }

  .card .info-text {
    flex: 1 1 60%;
    min-width: 0; 
  }

  .card .image-right {
    flex: 0 0 auto;
    align-self: flex-start;
  }

  .card .image-right img {
    max-width: 80%;
    height: auto;
  }

  .card .buttons-container {
    width: 100%;
    text-align: center;
    margin-top: 20px;
  }

  .card .buy-button,
  .card .buttons-container button {
    margin: 10px auto;
    display: inline-block;
  }
}
</style>

<div class="card">
<h2>{{ the_pokemon.name }}</h2>
    <div class="info-section">
        <div class="info-text">
            {% if the_pokemon.supertype %}
                <div class="info-label">Supertype:</div> {{ the_pokemon.supertype }}<br>
            {% endif %}

            {% if the_pokemon.subtypes %}
                <div class="info-label">Subtypes:</div>
                <ul class="subtypes">
                    {% for st in the_pokemon.subtypes %}
                    <li>{{ st }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if the_pokemon.types %}
                <div class="info-label">Types:</div>
                <ul class="types">
                    {% for type in the_pokemon.types %}
                        <span>{{ type }}</span>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if the_pokemon.hp >= 0 %}
                <div class="info-label">HP:</div> {{ the_pokemon.hp }}<br>
            {% endif %}

            {% if the_pokemon.flavorText %}
                <div class="info-label">Description:</div>
                <p>{{ the_pokemon.flavorText }}</p>
            {% endif %}


            {% if the_pokemon.evolves_from %}
                <div class="info-label">Evolves from:</div>
                {{ the_pokemon.evolves_from }}
            {% endif %}
            {% if the_pokemon.sell_price %}
                <div class="price">Current Price: {{ the_pokemon.sell_price }} </div>
            {% endif %}

            {% if the_pokemon.owner.username %}
                <div class="price">
                    Current Owner:
                    <a class="nametag" href="{% url 'profile' the_pokemon.owner.pk %}"> {{ the_pokemon.owner.username }}</a>
                </div>

            {% endif %}
        </div>
            <br><br>

        <div class="image-right">
            <img src="{{ the_pokemon.card.url }}" alt="{{ the_pokemon.name }}">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class = "buttons-container">
            {% if the_pokemon.owner == user %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="row justify-content-center">
                        <button class="sell-button" type="submit">Update Price</button>
                    </div>
                </form>
            {% else %}
                {% if the_pokemon.sell_price %}
                    <form method="post" action="{% url "trading:buy_single" the_pokemon.pk %}">
                        {% csrf_token %}
                        <div class="row justify-content-center">
                            <button class="buy-button" type="submit">Buy</button>
                        </div>
                    </form>
                {% endif %}
                {% if in_wishlist %}
                    <form method="post" action="{% url "trading:unwish" the_pokemon.pk %}">
                        {% csrf_token %}
                        <button class="sell-button" type="submit">Remove from Wishlist</button>
                    </form>
                {% else %}
                    <form method="post" action="{% url "trading:wish" the_pokemon.pk %}">
                        {% csrf_token %}
                        <button class="buy-button" type="submit">Add to wishlist</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
    <br>
    <br>
{% endblock %}

trading/templates/trading/pokemon_list.html
{% extends "base.html" %}

{% block title %}All Pokemons{% endblock %}

{% block content %}
    <style>
    .search-2 {
        position: relative;
        width: 100%;

    }

    .search-2 input {
        height: 45px;
        border: none;
        padding-right: 100px;
        border-radius: 10px;
    }

    .search-2 input:focus {
        border-color: none;
        box-shadow: none;
        outline: none;
    }

    .search-2 i {
        position: absolute;
        top: 12px;
        left: -10px;
        font-size: 24px;
        color: #eee;
    }

    .search-2 button {
        position: absolute;
        right: 3px;
        top: 5px;
        border: none;
        height: 35px;
        background-color: yellowgreen;
        color: black;
        width: 90px;
        border-radius: 10px
    }

    @media (max-width:800px) {
        .search-1 input {
            border-right: none;
            border-bottom: 1px solid #eee;
        }

        .search-2 i {
            left: 4px;
        }

        .search-2 input {
            padding-left: 34px;
        }

        .search-2 button {
            height: 35px;
            top: 5px;
        }

        .navbar-collapse {
            max-width: 80%;
        }

        .navbar_image {
            height: 15%;
            width: 15%;
        }

        .image-box {
            padding: 0px !important;
            border-radius: 9px;
            box-shadow: 0px 5px 16.2px -2px black;
            margin: 6px 15px 7px 0px;
            background-color: #F5F5D6;
        }
    }




    </style>
    <div class="container-fluid">
    <div class="container-fluid">
        <div class="d-flex justify-content-center">
            <h1 class="heading">All Pokemons</h1>
        </div>
        {% if not pokemons %}
            <div class="alert alert-info">
                {% if query_str %}
                    There are no such Pokemon
                {% else %}
                    There are no pokemons in this site.
                {% endif %}
            </div>
        {% endif %}
        <div class="row justify-content-center">
            <div class="">
                <div class="row">
                    <form class="search-2" method="GET">
                        <input type="text" name="s" placeholder="Search..." >
                        <button type="submit" >Search</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="card-deck">
            {% for pokemon in pokemons %}
                {% if pokemon.card %}
                    <div class="col-sm-2 image-box">
                        <img class="img-fluid" src="{{ pokemon.card.url }}" alt="Card image cap">
                        <span class="row-sm-3">
                            <a class="pokecardview" href="{% url "trading:single_detail" pokemon.pk %}"> View </a>

                        </span>

                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>



    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
        {% endif %}
    </ul>
    <em class="pagenum">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</em>
    </div>

{% endblock %}

trading/templates/trading/pokemon_update.html
{% extends "base.html" %}

{% block title %}sell{% endblock %}

{% block content %}
<h1>SellPokemom</h1>
<p><em>Setting a nonzero value puts your pokemon for sale, making it zero
    cancels the sale</em></p>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Price">
</form>
{% endblock %}